Run application with context aware backend
lorenzopappone/Context-aware-spell-checker pull request #28
Opened 2021-12-01 22:26 UTC by lorenzopappone

The application is now context-aware compliant. Major and minor modification has been implemented to adapt code to the context-aware backend.

2021-12-05 03:58 UTC, mfdunlap requested changes

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/_dictionary.py
>  import sys
Could you explain the reason behind the name change to _dictonary.py?

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/_dictionary.py
> +        root = configFile['DEFAULT']['root']
This is a good change so if we change the name of the folder we only have to change the name in one place!

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/routes.py
> +from flaskSpellChecker import utils
Isn't this already imported above in line 4?

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/routes.py
>  from configparser import ConfigParser
Do we need line 1 if we have line 7?

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/routes.py
> +        print("[DEBUG] misspelled words: ", misspellings.keys)
Are these checks to test to see if we are outputting the correct misspellings, wordIndexes, and candidates?

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/utils.py
> +
Should we also add the Irish dictionary here too?

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/utils.py
> +                misspellings[word] = corrections
So the corrections here are based on the context around the misspelling (the word before and after) so the corrections need to be tied to that context as well. If you remove the context from the result, you are also removing the whole purpose of the context aware.

2021-12-05 03:58 UTC, mfdunlap commented on flaskSpellChecker/utils.py
> +                misspellings[word] = corrections
If you remove that context, how do you know which correction list is appropriate (especially if the same word is misspelled multiple places)?

2021-12-06 23:22 UTC, lorenzopappone commented on flaskSpellChecker/_dictionary.py
>  import sys
The use of the underscore is just to specify that our dictionary file is different from the python dictionary built-in library. The names were in conflicts.

2021-12-06 23:22 UTC, lorenzopappone commented on flaskSpellChecker/routes.py
> +from flaskSpellChecker import utils
typos

2021-12-06 23:26 UTC, lorenzopappone commented on flaskSpellChecker/routes.py
> +        print("[DEBUG] misspelled words: ", misspellings.keys)
Where you see "debug" is just to check the returned variables type is what we need to be sent to front-end

2021-12-06 23:26 UTC, lorenzopappone commented on flaskSpellChecker/utils.py
> +
Yes, we can definitely.

2021-12-06 23:50 UTC, lorenzopappone commented on flaskSpellChecker/utils.py
> +                misspellings[word] = corrections
Front-end needs a list of misspelled words instead of contested. I agree for the same misspelled word case. I'll restore this lines, but I'll add some new lines in _routes.py_ where the misspellings.keys will be processed to extract only the misspelled from the contested words.

2021-12-07 05:44 UTC, manojv17 commented on flaskSpellChecker/routes.py
>  from configparser import ConfigParser
Line 4 still shows an error in my machine

2021-12-07 20:06 UTC, mfdunlap commented on flaskSpellChecker/_dictionary.py
>  import sys
Got it! Thanks for the clarification!

2021-12-07 20:09 UTC, mfdunlap commented on flaskSpellChecker/utils.py
> +                misspellings[word] = corrections
Sounds good! Thanks!

2021-12-08 21:21 UTC, merged